package com.example.accessingdatamysql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Service;

@Service
public class UserService {

	@Autowired // This means to get the bean called userRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

    @Cacheable(cacheNames="userCache", key="#id")
    public User getUserById(int id) {
        System.out.println("Getting user from DB");
        return userRepository.findById(id).get();
    }
}